User.create!([
  {email: "jeremydoranpeters@gmail.com", encrypted_password: "$2a$10$P8tQyr6Dd9zyEhdRGBffyOyeU/5NS64rXRhrEOY57ilk9dMk5AdVm", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 5, current_sign_in_at: "2015-03-18 00:34:00", last_sign_in_at: "2015-03-15 21:08:49", current_sign_in_ip: "::1", last_sign_in_ip: "::1", admin: true, allowed: true, first_name: "Jeremy", last_name: "Petfind", address: "3344", city: "chicago", state: "IN", zip_code: "3", phone: "6666666", boat_preference: "Island Time", group_id: 1},
  {email: "bob@aol.com", encrypted_password: "$2a$10$re5erfj5voLUzptUDuauleL.oFn0VDiyWXHtWpPBqkW.NcLLPfRVa", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2015-03-15 18:12:08", last_sign_in_at: "2015-03-15 18:12:08", current_sign_in_ip: "::1", last_sign_in_ip: "::1", admin: false, allowed: false, first_name: "Bob", last_name: "Elroy", address: "55 Davais", city: "Joliet", state: "IL", zip_code: "60901", phone: "7777777777", boat_preference: "Island Time", group_id: 2},
  {email: "mary@aol.com", encrypted_password: "$2a$10$zgZ587yIx.qX/8RvWFG5veDgWltRQ1SGkLIQsfHIL7GHVEiUw.Vsq", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2015-03-17 02:29:54", last_sign_in_at: "2015-03-17 02:29:54", current_sign_in_ip: "::1", last_sign_in_ip: "::1", admin: false, allowed: false, first_name: "Mary", last_name: "Jane", address: "4444 stone", city: "LaGrange", state: "IL", zip_code: "598855`", phone: "588688", boat_preference: "Ah Cha", group_id: 2},
  {email: "jay@acltc.com", encrypted_password: "$2a$10$x/.bNNg/Ixe0tBRxFx7KfeoaFrIodNZyEDJHxXxJfEczrG4XMqYsy", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2015-03-18 20:11:01", last_sign_in_at: "2015-03-18 20:11:01", current_sign_in_ip: "::1", last_sign_in_ip: "::1", admin: false, allowed: false, first_name: "Jay", last_name: "Wengrow", address: "Merch Mart", city: "Chciago", state: "IL", zip_code: "60666", phone: "55555555", boat_preference: "Ah Cha", group_id: 3},
  {email: "dirk@digler.com", encrypted_password: "$2a$10$p5jemBl/IfmuRYn3O5WMG.PJcu9wYw2flvk3ccINu3i0US2VbKvBa", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2015-03-18 20:28:17", last_sign_in_at: "2015-03-18 20:28:17", current_sign_in_ip: "::1", last_sign_in_ip: "::1", admin: false, allowed: false, first_name: "Dirk ", last_name: "Digler", address: "23323", city: "chicago", state: "il", zip_code: "34251234", phone: "34513532", boat_preference: "incredible", group_id: 3}
])
Boat.create!([
  {image_url: "http://i.imgur.com/nNnT2SJ.jpg", name: "Paper Tiger", make: "Morgan", size: 42, shares_possible: 8, full_share_price: "4350.0", two_thirds_share_price: "3250.0", harbor: "Monroe", half_credit_AM_MTWTH: 14, half_credit_PM_MTWTH: 14, half_credit_AM_F: 14, half_credit_PM_F: 18, half_credit_AM_SAT: 20, half_credit_PM_SAT: 20, half_credit_AM_SUN: 19, half_credit_PM_SUN: 19, full_credit_MTWTH: 20, full_credit_F: 27, full_credit_SAT: 33, full_credit_SUN: 30, two_thirds_credits_total: 195, full_credits_total: 290, service_notes: nil, current_status: "not checked out", one_day_out: true},
  {image_url: "http://i.imgur.com/lypHyk5.jpg", name: "Cloudsplitter", make: "Islander", size: 36, shares_possible: 8, full_share_price: "3850.0", two_thirds_share_price: "2850.0", harbor: "Monroe", half_credit_AM_MTWTH: 13, half_credit_PM_MTWTH: 13, half_credit_AM_F: 13, half_credit_PM_F: 16, half_credit_AM_SAT: 19, half_credit_PM_SAT: 19, half_credit_AM_SUN: 16, half_credit_PM_SUN: 16, full_credit_MTWTH: 20, full_credit_F: 25, full_credit_SAT: 29, full_credit_SUN: 29, two_thirds_credits_total: 180, full_credits_total: 270, service_notes: nil, current_status: "not checked out", one_day_out: true},
  {image_url: "http://i.imgur.com/MUEgc7n.jpg", name: "Ah Cha", make: "Islander", size: 36, shares_possible: 8, full_share_price: "3850.0", two_thirds_share_price: "2850.0", harbor: "Monroe", half_credit_AM_MTWTH: 13, half_credit_PM_MTWTH: 13, half_credit_AM_F: 13, half_credit_PM_F: 16, half_credit_AM_SAT: 19, half_credit_PM_SAT: 19, half_credit_AM_SUN: 16, half_credit_PM_SUN: 16, full_credit_MTWTH: 20, full_credit_F: 25, full_credit_SAT: 29, full_credit_SUN: 29, two_thirds_credits_total: 180, full_credits_total: 270, service_notes: nil, current_status: "not checked out", one_day_out: true},
  {image_url: "http://i.imgur.com/jGNZlBV.jpg", name: "Sea Dancer", make: "C & C", size: 33, shares_possible: 8, full_share_price: "3950.0", two_thirds_share_price: "2950.0", harbor: "31st", half_credit_AM_MTWTH: 13, half_credit_PM_MTWTH: 13, half_credit_AM_F: 13, half_credit_PM_F: 16, half_credit_AM_SAT: 19, half_credit_PM_SAT: 19, half_credit_AM_SUN: 16, half_credit_PM_SUN: 16, full_credit_MTWTH: 20, full_credit_F: 25, full_credit_SAT: 29, full_credit_SUN: 29, two_thirds_credits_total: 180, full_credits_total: 270, service_notes: nil, current_status: "not checked out", one_day_out: true},
  {image_url: "http://i.imgur.com/c5rdbSu.jpg", name: "Aquavit", make: "Morgan", size: 33, shares_possible: 8, full_share_price: "2750.0", two_thirds_share_price: "2150.0", harbor: "Monroe", half_credit_AM_MTWTH: 8, half_credit_PM_MTWTH: 8, half_credit_AM_F: 8, half_credit_PM_F: 12, half_credit_AM_SAT: 14, half_credit_PM_SAT: 14, half_credit_AM_SUN: 12, half_credit_PM_SUN: 12, full_credit_MTWTH: 13, full_credit_F: 18, full_credit_SAT: 24, full_credit_SUN: 21, two_thirds_credits_total: 120, full_credits_total: 180, service_notes: "Dry docked for repairs - thanks to Jeremy's dumb ass", current_status: "offline", one_day_out: false},
  {image_url: "http://i.imgur.com/yS61Afm.jpg", name: "Playful Tiger", make: "Morgan", size: 321, shares_possible: 8, full_share_price: nil, two_thirds_share_price: nil, harbor: "Holland", half_credit_AM_MTWTH: nil, half_credit_PM_MTWTH: nil, half_credit_AM_F: nil, half_credit_PM_F: nil, half_credit_AM_SAT: nil, half_credit_PM_SAT: nil, half_credit_AM_SUN: nil, half_credit_PM_SUN: nil, full_credit_MTWTH: nil, full_credit_F: nil, full_credit_SAT: nil, full_credit_SUN: nil, two_thirds_credits_total: nil, full_credits_total: nil, service_notes: nil, current_status: "not checked out", one_day_out: true},
  {image_url: "http://imgur.com/fOkOQUe.jpg", name: "Incredible", make: "Ranger", size: 29, shares_possible: 8, full_share_price: "2550.0", two_thirds_share_price: "1950.0", harbor: "Monroe", half_credit_AM_MTWTH: 8, half_credit_PM_MTWTH: 8, half_credit_AM_F: 8, half_credit_PM_F: 12, half_credit_AM_SAT: 14, half_credit_PM_SAT: 14, half_credit_AM_SUN: 12, half_credit_PM_SUN: 12, full_credit_MTWTH: 13, full_credit_F: 18, full_credit_SAT: 24, full_credit_SUN: 21, two_thirds_credits_total: 120, full_credits_total: 180, service_notes: nil, current_status: "not checked out", one_day_out: true},
  {image_url: "http://i.imgur.com/v4aP7g0.jpg", name: "Whirlaway", make: "Catalina", size: 27, shares_possible: 8, full_share_price: "1975.0", two_thirds_share_price: "1150.0", harbor: "Monroe", half_credit_AM_MTWTH: 6, half_credit_PM_MTWTH: 6, half_credit_AM_F: 6, half_credit_PM_F: 10, half_credit_AM_SAT: 12, half_credit_PM_SAT: 12, half_credit_AM_SUN: 10, half_credit_PM_SUN: 10, full_credit_MTWTH: 10, full_credit_F: 13, full_credit_SAT: 18, full_credit_SUN: 16, two_thirds_credits_total: 70, full_credits_total: 140, service_notes: nil, current_status: "not checked out", one_day_out: true},
  {image_url: nil, name: "michael", make: "", size: nil, shares_possible: nil, full_share_price: nil, two_thirds_share_price: nil, harbor: "", half_credit_AM_MTWTH: nil, half_credit_PM_MTWTH: nil, half_credit_AM_F: nil, half_credit_PM_F: nil, half_credit_AM_SAT: nil, half_credit_PM_SAT: nil, half_credit_AM_SUN: nil, half_credit_PM_SUN: nil, full_credit_MTWTH: nil, full_credit_F: nil, full_credit_SAT: nil, full_credit_SUN: nil, two_thirds_credits_total: nil, full_credits_total: nil, service_notes: nil, current_status: "not checked out", one_day_out: true},
  {image_url: "http://www.sailingnj.com/wp-content/uploads/2011/09/DSC_0083.jpg", name: "Island Time", make: "Catalina", size: 30, shares_possible: 8, full_share_price: "3000.0", two_thirds_share_price: "2700.0", harbor: "Monroe", half_credit_AM_MTWTH: 12, half_credit_PM_MTWTH: 12, half_credit_AM_F: 14, half_credit_PM_F: 14, half_credit_AM_SAT: 16, half_credit_PM_SAT: 16, half_credit_AM_SUN: nil, half_credit_PM_SUN: nil, full_credit_MTWTH: 22, full_credit_F: 25, full_credit_SAT: 28, full_credit_SUN: 25, two_thirds_credits_total: 190, full_credits_total: 270, service_notes: "This boat does not exist", current_status: "offline", one_day_out: false},
  {image_url: "http://www.krmsradio.com/wp-content/uploads/2014/08/sailboat.jpg", name: "aefds", make: "asdfasd", size: 0, shares_possible: 0, full_share_price: nil, two_thirds_share_price: nil, harbor: "adsfq", half_credit_AM_MTWTH: nil, half_credit_PM_MTWTH: nil, half_credit_AM_F: nil, half_credit_PM_F: nil, half_credit_AM_SAT: nil, half_credit_PM_SAT: nil, half_credit_AM_SUN: nil, half_credit_PM_SUN: nil, full_credit_MTWTH: nil, full_credit_F: nil, full_credit_SAT: nil, full_credit_SUN: nil, two_thirds_credits_total: nil, full_credits_total: nil, service_notes: "This boat does not exist", current_status: "offline", one_day_out: true}
])
Group.create!([
  {boat_assigned: "Aha Cha", credits: 120, full_share: false, two_thirds_share: true},
  {boat_assigned: "Incredible", credits: 180, full_share: false, two_thirds_share: true},
  {boat_assigned: "Paper Tiger", credits: 120, full_share: false, two_thirds_share: true}
])
